[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -u main_railway.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# 环境变量
[variables]
PORT = "8000"
DATABASE_URL = "/app/data/side_by_side.db"
UPLOAD_PATH = "/app/data/uploads"
EXPORT_PATH = "/app/data/exports"
# 修复Volume权限问题（根据Railway官方文档）
RAILWAY_RUN_UID = "0"

# Volume 配置 - 持久化存储（Railway Hobby计划）
[[volumes]]
name = "app-data"
mountPath = "/app/data"