[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python -u main_railway.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

# 环境变量
[variables]
PORT = "8000"
DATABASE_URL = "/app/data/side_by_side.db"
UPLOAD_PATH = "/app/data/uploads"
EXPORT_PATH = "/app/data/exports"

# Volume 配置 - 持久化存储
[[volumes]]
name = "app-data"
mountPath = "/app/data"